version: "3"

services:
  app:
    depends_on:
      - 'mongo'
    build: .
    volumes:
      - ./app:/usr/src/app
    ports:
      - "9080:80"
    command: yarn start
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"